export const FEATURE_FLAGS = {
  STREAMING_ENABLED: 'STREAMING_ENABLED',
  PAGINATION_LIMIT: 'PAGINATION_LIMIT',
  CHAT_HISTORY_ENABLED: 'CHAT_HISTORY_ENABLED',
  AI_TOOLS_ENABLED: 'AI_TOOLS_ENABLED',
} as const;
